/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#f3bc82",
        "on-tertiary-fixed": "#390b0e",
        "error-container": "#ffdad6",
        "surface-tint": "#2c694e",
        "sand-light": "#F4F1DE",
        "surface-bright": "#f8faf6",
        "on-tertiary-container": "#ffcfce",
        "tertiary": "#713638",
        "error": "#ba1a1a",
        "surface-container-high": "#e7e9e5",
        "on-secondary-fixed-variant": "#643f10",
        "secondary-fixed": "#ffdcbb",
        "on-primary-container": "#a8e7c5",
        "surface": "#f8faf6",
        "on-surface-variant": "#404943",
        "on-surface": "#191c1a",
        "waste-paper": "#E9C46A",
        "primary-fixed-dim": "#95d4b3",
        "primary": "#0f5238",
        "on-secondary": "#ffffff",
        "background": "#f8faf6",
        "surface-variant": "#e1e3df",
        "on-tertiary-fixed-variant": "#6f3537",
        "tertiary-fixed": "#ffdad9",
        "surface-dim": "#d8dbd7",
        "organic-mint": "#D8F3DC",
        "inverse-primary": "#95d4b3",
        "on-primary-fixed-variant": "#0e5138",
        "earth-clay": "#8D6E63",
        "on-error": "#ffffff",
        "inverse-surface": "#2e312f",
        "primary-container": "#2d6a4f",
        "surface-container": "#eceeea",
        "on-primary": "#ffffff",
        "outline": "#707973",
        "on-primary-fixed": "#002114",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "secondary": "#7f5626",
        "secondary-container": "#ffc78c",
        "tertiary-fixed-dim": "#ffb3b3",
        "on-background": "#191c1a",
        "nature-leaf": "#40916C",
        "waste-plastic": "#3A86FF",
        "tertiary-container": "#8d4d4e",
        "inverse-on-surface": "#eff1ed",
        "outline-variant": "#bfc9c1",
        "surface-container-highest": "#e1e3df",
        "on-secondary-container": "#795121",
        "waste-organic": "#A3B18A",
        "primary-fixed": "#b1f0ce",
        "on-secondary-fixed": "#2b1700",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f2f4f0"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-max": "1280px",
        "margin-mobile": "1rem",
        "component-gap": "1rem",
        "section-gap": "5rem",
        "margin-desktop": "2.5rem",
        "gutter": "1.5rem"
      },
      "fontFamily": {
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "stat-number": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "stat-number": ["40px", {"lineHeight": "40px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
